;Autores: 
;Bruno Cattalini
;Lucas Kaniak

; Lista no formato:
; ((Grau (Ver1 Val1) (Ver2 Val2) [...])(Proximidade (Ver1 Val1) (Ver2 Val2) [...])(Intermediacao (Ver1 Val1) (Ver2 Val2) [...]))
; Para teste: (setq teste '(("Grau" (9999 8) (156 6) (22 6))("Proximidade" (18 4.76) (170 4.52) (1500 4.44))("Intermediacao" (90 4.42) (76 38) (5 37))))

(defun print_saida (tabela)
	(setq a (car tabela))
	(setq b (cadr tabela))
	(setq c (caddr tabela))
	(if (eq (car a) "Proximidade")
		(if (eq (car b) "Intermediacao")(print_tabela c a b)
			(print_tabela b a c)
		)
		(if (eq (car a) "Intermediacao")
			(if (eq (car b) "Proximidade")(print_tabela c b a)
				(print_tabela b c a)
			)
			(if (eq (car b) "Proximidade")(print_tabela a b c)
				(print_tabela a c b)
			)
		)
	)
)


(defun print_tabela (coluna1 coluna2 coluna3)
	(setq cab1 "Vertice")
	(setq cab2 "Valor")
	(setq t1 (list (car coluna1)))
	(setq t2 (list (car coluna2)))
	(setq t3 (list (car coluna3)))
	(format t "~v,,,vA~%" 72 #\_ #\space)
	(format t "|~{          ~A         ~}" t1)
	(format t "|~{     ~A     ~}" t2)
	(format t "|~{      ~A      |~}~%" t3)
	(format t "~v,,,vA~%" 72 #\- #\space)
	(format t "~C" #\|)
	(dotimes (cont 2) (progn (format t "  ~A  |" cab1) (format t "   ~A   |" cab2)))
	(format t "  ~A  |" cab1)
	(format t "   ~A   |~%" cab2)
	(format t "~v,,,vA~%" 72 #\- #\space)
	(setq coluna1  (cdr coluna1))
	(setq coluna2 (cdr coluna2))
	(setq coluna3 (cdr coluna3))
	(setq tabela (list coluna1 coluna2 coluna3))
	;(mapcar (lambda (&rest arg)(format t "~A" arg)) tabela)
	(loop for x in coluna1
		  for y in coluna2
		  for z in coluna3
		  do
		  (format t "|") 
		  (format_control (car x))
		  (format_control (cadr x))
		  (format_control (car y))
		  (format_control (cadr y))
		  (format_control (car z))
		  (format_control (cadr z)) 
		  (format t "~%")
	)
	(format t "~v,,,vA~%" 72 #\- #\space)
	T
)

(defun format_control (num)
	(if (floatp num)
		(if (< (- num 10) 0)			(format t "    ~,2F   |" num) ;(un)
			(if (< (- num 100) 0)		(format t "   ~,2F   |" num) ;(dec)
				(if (< (- num 1000) 0)	(format t "   ~,2F  |" num) ;(cent)
										(format t "  ~,2F  |" num) ;(mili)
				)
			)
		)
		(if (< (- num 10) 0)			(format t "     ~A     |" num) ;(un)
			(if (< (- num 100) 0)		(format t "     ~A    |" num) ;(dec)
				(if (< (- num 1000) 0)	(format t "    ~A    |" num) ;(cent)
										(format t "    ~A   |" num) ;(mili)
				)
			)
		)
	)
)
